Fix/update spring
boomerang-io/flow.service.workflow pull request #174
Opened 2022-04-13 11:44 UTC by AndreiOla

**Changed**
Updated Spring to 5.2.2.20, in order to fic critical vulnerability.

2022-04-13 11:54 UTC, tlawrie commented
Hi @AndreiOla this seems to have a number of other changes not related to the dependency change. Could you clarify?

2022-04-13 11:58 UTC, AndreiOla commented
Hi @tlawrie I made changes starting from tag 2.8.3.7. And I want to build only those changes, on top of tag 2.8.3.7. I was just trying to figure out how can I do that, since git does not allow me to open a PR against a certain tag.

2022-04-13 22:47 UTC, tlawrie commented
So typically you would create a branch from the tag i.e. 

```
git checkout <tag>
git checkout -b fix-<branch_name>
```

And then when you tag it, it would be the original <tag> and then either a fourth hot fix number like `.1` or `-fix.1` or something like that

2022-04-14 06:38 UTC, AndreiOla commented
Thanks @tlawrie !
I made separate branches from the tags in my fork, made changes, and then used @amhudson branches in (https://github.com/boomerang-io/flow.service.workflow), for the tag, since I do not have sufficient rights to push into (https://github.com/boomerang-io/flow.service.workflow) directly.
That is correct, that we don't need to merge into main. Just build hot fixes for those tags.

2022-04-14 13:10 UTC, amhudson commented
@tlawrie yes, that's correct

2022-04-14 13:26 UTC, amhudson requested changes

2022-04-14 13:26 UTC, amhudson commented on pom.xml
>  		<log4j2.version>2.17.2</log4j2.version>
there are 2 `log4j2.version`, remove `2.17.0`.

2022-04-14 13:37 UTC, AndreiOla commented on pom.xml
>  		<log4j2.version>2.17.2</log4j2.version>
Fixed.

2022-04-14 13:38 UTC, amhudson approved these changes

2022-04-14 13:40 UTC, merged